# 2024-11-29 Kiri, All rights reserved.

AUTO = 'auto'
KOREAN = 'ko'
ENGLISH = 'en' 
JAPANESE = 'ja'
CHINESE_SIMPLIFIED = 'zh-CN' 
CHINESE_TRADITIONAL = 'zh-TW'
SPANISH = 'es'
FRENCH = 'fr'
GERMAN = 'de'
RUSSIAN = 'ru'
PORTUGUESE = 'pt'
ITALIAN = 'it'
VIETNAMESE = 'vi'
THAI = 'th'
INDONESIAN = 'id'
HINDI = 'hi'
ARABIC = 'ar'